Repository JuliaSmoothOptimizers/LinearOperators.jl, pull requests merged in 2024-02, with the labels that each got.

#310 Use CITATION.cff
  CITATION.bib
  CITATION.cff
  README.md
Labels: documentation

#311 Fix documentation build
  docs/src/index.md
  docs/src/tutorial.md
Labels: bug, documentation

#317 update CirrusCI config
  .cirrus.yml
Labels: CI
